# Generated by Django 6.1 on 2026-08-30 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mehmonxona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=150)),
                ('manzil', models.CharField(max_length=255)),
                ('malumot', models.TextField()),
                ('yulduz_soni', models.PositiveIntegerField(default=5)),
                ('xona_soni', models.PositiveIntegerField()),
                ('bir_kunlik_narx', models.DecimalField(decimal_places=2, max_digits=10)),
                ('wifi_bormi', models.BooleanField(default=True)),
                ('emaili', models.EmailField(max_length=254)),
                ('ochilgan_sana', models.DateTimeField()),
                ('yaratilgan_vaqt', models.DateTimeField(auto_now_add=True)),
                ('yangilangan_vaqt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
